name: mSit
description: Fun based plugin to make players sit.
version: '${project.version}'
main: me.meiallu.msit.MSit
author: Meiallu
commands:
  sit:
    description: Will make you sit on the ground.
    usage: /sit
    permission: msit.use
